server {
    listen       80;
    server_name  _;
    root   /data/app;

    location /adminPlatform {
        alias /data/app;

        location ~* \.(js|css)$ {
            try_files $uri =403;
        }

        try_files $uri $uri/ /index.html;
    }
}
